### PR TITLE
fix(controller): prevent accidental deletion of adopted PVCs

### LINKED ISSUE #255: Unable to use existing PVC
Hey,

I'm not sure if this a documentation issue or a bug in the operator, but when I set persistence to enabled and to use existing PVC, it attempts to delete the PVC regardless, then create a new one. If the PVC name happens to be the same (e.g. `pocketid-data` as mine was) then this causes CI/CD tools like argocd to get stuck trying to re-create the PVC as defined in the manifests and the operator trying to delete and recreate it itself.

I expected 'existingClaim' to use the existing PVC, not to delete it. I don't have a workaround that can actually use the existing volume for me in this case.

### PR DESCRIPTION
**Pull request by justin8**
## Summary
This PR fixes a bug in the PocketIDInstance controller where the operator would accidentally delete a PersistentVolumeClaim (PVC) if it was named according to the operator's default convention (<instance-name>-data) and then specified in spec.persistence.existingClaim.

## The Problem
When a user attempted to "adopt" a PVC that was either previously managed by the operator or manually created with the standard naming convention, the reconcileVolume logic would unconditionally attempt to delete any PVC matching the default name if existingClaim was set. This caused:
1. The desired PVC to be placed in a Terminating state.
2. The PersistentVolume (PV) to hang with a dangling reference to the deleted PVC.
3. The PocketID Pod to fail to start because it could not mount the terminating PVC.

## Changes
- Modified reconcileVolume: Added a check to ensure the default PVC is only deleted if its name differs from the one specified in existingClaim.
- Improved Management: If the existingClaim matches the default name, the operator now gracefully stops managing that PVC's lifecycle (labels/ownership) without deleting the underlying resource.
- Added Regression Tests: 
  - Verified that an existing PVC with the default name is not deleted when referenced via existingClaim.
  - Verified that switching from a default PVC to a different existingClaim correctly triggers the cleanup of the old, unused PVC.

Fixes #255

### CODE REVIEW

File: internal/controller/instance/controller.go [hunk 1]
```diff
@@ -639,23 +639,38 @@ func isHTTPRouteCRDUnavailableError(err error) bool {
...
+	// If using an existing claim, delete the default PVC ONLY if its name is different from the existing claim
+	if instance.Spec.Persistence.ExistingClaim != "" {
+		if instance.Spec.Persistence.ExistingClaim != defaultPVCName {
+			log.V(1).Info("Deleting default PVC (using different existingClaim)", "pvc", defaultPVCName, "existingClaim", instance.Spec.Persistence.ExistingClaim)
+			err := r.Delete(ctx, pvc)
+			return client.IgnoreNotFound(err)
+		}
+		// If they are the same, we just stop managing it
+		log.V(1).Info("Stopping management of default PVC (used as existingClaim)", "pvc", defaultPVCName)
+		return nil
```
Comment (aclerici38) [inline internal/controller/instance/controller.go:684]: Should the ownerRef/managed-by labels get removed here as well? e.g. operator creates pvc, admin moves it to `existingClaim` -> it would get cleaned up on garbage collection if the instance is deleted. It's for sure an edge case but I can see someone trying to work around reusing the pvc in that way

**Comment by aclerici38** [comment]
Thanks a ton @justin8 I completely missed that. Sorry for any issues it caused

File: internal/controller/instance/controller.go (hunk 1 above)
Comment (justin8) [reply internal/controller/instance/controller.go:684]: That's a good point. I'll push an update

**Comment by justin8** [comment]
No problem, it's working pretty well for me now after fixing this. Thanks for building it!

**Review by aclerici38 — APPROVED** [review]
